---
- name: Calling Groovy script {{ script_name }}
  uri:
    url: "{{hostvars.nexus.private_uri}}{{ nexus_rest_api_endpoint }}/script/{{ script_name }}/run"
    user: 'admin'
    password: "{{ current_nexus_admin_password }}"
    headers:
      Content-Type: "text/plain"
    method: POST
    status_code: 200,204
    force_basic_auth: yes
    body: "{{ args | to_json }}"
